Hamburger_site_MVC/Controllers/BurgerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hamburger_site_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hamburger_site_MVC.Controllers
{
    public class BurgerController : Controller
    {
        private readonly IBurgerRepository _burgerRepository;

        public BurgerController(IBurgerRepository burgerRepository)
        {
            _burgerRepository = burgerRepository;
        }

        public IActionResult BurgerList()
        {
            return View(_burgerRepository.AllBurger);
        }

        public IActionResult BurgerDetail(int id)
        {
            var burger = _burgerRepository.GetBurgerById(id);

            if (burger == null)
                return NotFound();

            return View(burger);
        }
    }
}

Hamburger_site_MVC/Controllers/ShoppingCartController.cs
using Hamburger_site_MVC.Models;
using Hamburger_site_MVC.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hamburger_site_MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBurgerRepository _burgerRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IBurgerRepository burgerRepository, ShoppingCart shoppingCart)
        {
            _burgerRepository = burgerRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int burgerId)
        {
            var selectedBurger = _burgerRepository.AllBurger.FirstOrDefault(p => p.BurgerId == burgerId);

            if (selectedBurger != null)
            {
                _shoppingCart.AddToCart(selectedBurger, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int burgerId)
        {
            var selectedBurger = _burgerRepository.AllBurger.FirstOrDefault(p => p.BurgerId == burgerId);

            if (selectedBurger != null)
            {
                _shoppingCart.RemoveFromCart(selectedBurger);
            }
            return RedirectToAction("Index");
        }
    }
}

Hamburger_site_MVC/Views/Shared/_BurgerCard.cshtml
@model Burger

<div class="col-md-4 col-lg-3 burgerCard">
    <img src="@Model.ImageUrl" alt="@Model.ImageAlt" />
    <h1>
        <a asp-controller="Burger"
           asp-action="BurgerDetail"
           asp-route-id="@Model.BurgerId">@Model.Name</a>
    </h1>
    <p>@Model.Description</p>
    <h2>@Model.Price.ToString("c")</h2>
    <div class="addToCart">
        <p class="button">
            <a class="btn btn-primary"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-burgerId="@Model.BurgerId">Add to cart</a>
        </p>
    </div>
</div>

Hamburger_site_MVC/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-8">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="slide-image" src="~/Images/banner_1.jpg" alt="Banner_1">
                </div>
                <div class="carousel-item">
                    <img class="slide-image" src="~/Images/banner_2.jpg" alt="Banner_2">
                </div>
                <div class="carousel-item">
                    <img class="slide-image" src="~/Images/banner_3.jpg" alt="Banner_3">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

Hamburger_site_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hamburger_site_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hamburger_site_MVC</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Burger" asp-action="BurgerList">Menu</a>
                            </li>
                            @await Component.InvokeAsync("ShoppingCartSummary")
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="row centralize">
            <div class="col-md-3">
                <p class="lead">
                    <img class="logo-img" alt="Burger Logo" src="~/Images/logo.png" />
                </p>
                <span class="glyphicon glyphicon-shopping-cart"></span>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Hamburger_site_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        @RenderSection("Scripts", required: false)
        <script src="~/js/site.js" asp-append-version="true"></script>
    </div>
</body>
</html>